[tool.poetry]
name = "pheval_elder"
version = "0.1.0"
description = ""
authors = ["iQuxLE <ckroll95@gmail.com>"]
readme = "README.md"
packages = [{ include = "pheval_elder", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
chromadb = "^0.4.20"
jupyter = "^1.0.0"
np = "^1.0.2"
pandas = "^2.1.4"
pheval = "^0.3.2"

[tool.poetry.plugins."pheval.plugins"]
customrunner = "pheval_elder.runner:ElderPhEvalRunner"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
